config/routes.rb
Rails.application.routes.draw do

  resources :show_results
  resources :overtimes, :except => [:index, :edit, :show, :new]
  resources :vacations, :except => [:index, :edit, :show, :new]
  resources :report_results, :except => [:edit, :show, :destroy]
  resources :global_settings do
    collection do
      get :get, to: "global_settings#get"
    end
  end
  resources :issues
  resources :issue_histories
  resources :businesses, :except => [:show, :destroy, :create, :new]

  resources :report_types
  resources :components, :except => [:edit, :show, :update, :destroy, :new] 
  resources :projects, :except => [:show]

  resources :statuses, :except => [:show] do
    collection do
      get :refresh, to: "statuses#refresh"
    end
  end
  
  resources :reports do 
    get :get_report, to: "reports#get_report"
    get :get_results, to: "reports#get_results"
  end
  get 'reports/index'

  resources :employees, :except => [:destroy, :create, :new] do
    get :hide_and_show
    collection do
      get :refresh, to: "employees#refresh"
    end
  end

  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations",
    :unlocks => "users/unlocks",
    :omniauth => "users/omniauth"
  } 

  devise_scope :user do
    # get 'signup', to: "users/registrations#new"
    # get 'signin', to: "users/sessions#new"
    get 'users/sign_out', to: "users/sessions#destroy"
  end

  resources :users
    
  root 'reports#index'
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :issue_histories

  has_many :employees_report_types
  has_many :report_types, through: :employees_report_types

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employee, only: [:show, :edit, :update]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
    @show_all = false
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee_issues = Array.new
    IssueHistory.where("employee_id = ?", @employee.id).each do |ih| 
      @employee_issues.push(Issue.find(IssueHistory.find(ih.id).issue_id).issue_key)
    end
  end

  # GET /employees/1/edit
  def edit
  end

  # PATCH/PUT /employees/1 change the status of the employee
  def hide_and_show
    @employee = Employee.find(params[:employee_id])
    @employee.hide = !@employee.hide

    respond_to do |format|
      if @employee.save
        format.html do
          redirect_to employees_path
        end
        format.json { render json: @employee.to_json}
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /employees#refresh
  def refresh
    connect_to_jira = GetJiraResponseService.new
    Project.all.each do |project|
      employees = connect_to_jira.employees(project.prefix)
      employees.each do |employee|
        if Employee.find_by_email(employee['emailAddress']).nil?
          e = Employee.new(name: employee['name'], email: employee['emailAddress'], key: employee['key'], display_name: employee['displayName'], active: employee['active'])
          e.save!
        end
      end
    end
    redirect_to employees_path, notice: 'Employees was successfully updated'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_params
    params.require(:employee).permit(:name, :email, :hide, :key, :display_name, :active)
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= f.fields_for :employees do |f| %>
  <%= f.label :Jira_user %>
  <%= f.text_field :name, value: @employee.name, :class => "form-control" %>
  <%= f.label :email %>
  <%= f.text_field :email, value: @employee.email, :class => "form-control", :readonly => true %>
  <%= f.label "Activity status" %>
  <%= f.text_field :active, value: @employee.active, :class => "form-control", :readonly => true %>
  <%= f.label "Hide?" %>
  <%= f.select(:hide, options_for_select([['Yes', true], ['No', false]], {:selected => @employee.hide})) %>
<% end %>

app/views/employees/edit.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Edit Employee") %>
  <center><h1>Edit employee</h1></center>
  <%= form_for @employee do |f| %>
    <%= render 'shared/error_messages' %>
    <%= render 'employees/form', f: f %>
    <%= f.submit "Save", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Employees")%>
  <center><h1>Employees</h1></center>
  <%= link_to 'Refresh', refresh_employees_path %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Status</th>
        <th>Jira key</th>
        <th>Jira display name</th>
        <th>Hide?</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <% if !employee.hide && !@show_all %>
          <tr>
            <td><%= link_to employee.name, employee_path(employee) %></td>
            <td><%= employee.email %></td>
            <td>
              <% if employee.active? %>
               <font color="#17CA05">Active</font>
              <% else %>
                <font color="#C60606">Inactive</font>
              <% end %>
            </td>
            <td><%= employee.key %></td>
            <td><%= employee.display_name %></td>
            <td><%= link_to 'Hide', employee_hide_and_show_path(employee) %></td>
            <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
          </tr>
        <% else %>
          <tr>
            <td><%= employee.name %></td>
            <td><%= employee.email %></td>
            <td>
              <% if employee.active? %>
               <font color="#17CA05">Active</font>
              <% else %>
                <font color="#C60606">Inactive</font>
              <% end %>
            </td>
            <td><%= employee.key %></td>
            <td><%= employee.display_name %></td>
            <% if employee.hide %>
              <td><%= link_to 'Show', employee_hide_and_show_path(employee) %></td>
            <% else %>
              <td><%= link_to 'Hide', employee_hide_and_show_path(employee) %></td>
            <% end %>
            <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Refresh', refresh_employees_path %>
</div>

app/views/employees/show.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Employee show")%>
  <center><h1><%= @employee.display_name %></h1></center>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Active?</th>
        <th>Issues</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @employee.name %></td>
        <td><%= @employee.email %></td>
        <td><%= @employee.active %></td>
        <td>
          <% @employee_issues.distinct.each do |ei| %>
            <%= ei %>
          <% end %>
        </td>
        <td><%= button_to 'Edit', edit_employee_path(@employee), method: :get, class: 'btn btn-info btn-xs' %></td>
      </tr>
    </tbody>
  </table>
</div>
<%= link_to 'Back', employees_path %>