config/routes.rb
Rails.application.routes.draw do

  resources :show_results
  resources :overtimes, :except => [:index, :edit, :show, :new]
  resources :vacations, :except => [:index, :edit, :show, :new]
  resources :report_results, :except => [:edit, :show, :destroy]
  resources :global_settings do
    collection do
      get :get, to: "global_settings#get"
    end
  end
  resources :issues
  resources :issue_histories
  resources :businesses, :except => [:show, :destroy, :create, :new]

  resources :report_types
  resources :components, :except => [:edit, :show, :update, :destroy, :new] 
  resources :projects, :except => [:show]

  resources :statuses, :except => [:show] do
    collection do
      get :refresh, to: "statuses#refresh"
    end
  end
  
  resources :reports do 
    get :get_report, to: "reports#get_report"
    get :get_results, to: "reports#get_results"
  end
  get 'reports/index'

  resources :employees, :except => [:destroy, :create, :new] do
    get :hide_and_show
    collection do
      get :refresh, to: "employees#refresh"
    end
  end

  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations",
    :unlocks => "users/unlocks",
    :omniauth => "users/omniauth"
  } 

  devise_scope :user do
    # get 'signup', to: "users/registrations#new"
    # get 'signin', to: "users/sessions#new"
    get 'users/sign_out', to: "users/sessions#destroy"
  end

  resources :users
    
  root 'reports#index'
end

app/models/issue.rb
class Issue < ApplicationRecord
  has_many :issue_histories
  has_many :components_issues
  has_many :components, through: :components_issues
  has_many :businesses_issues
  has_many :businesses, through: :businesses_issues
  has_many :projects

  validates_uniqueness_of :issue_key
  validates_uniqueness_of :jira_id_tag

  paginates_per = 50

  def self.search(term, page)
    if term
      where('issue_key LIKE ?', :term).order('issue_key ASC').page(current_page)
    else
      # note: default is all, just sorted
      order('issue_key ASC').page(current_page) 
    end
  end
end

app/models/report_type.rb
class ReportType < ApplicationRecord
  has_many :employees_report_types
  has_many :employees, through: :employees_report_types
  has_many :components_report_types
  has_many :components, through: :components_report_types
  has_many :businesses_report_types
  has_many :businesses, through: :businesses_report_types
  has_many :projects_report_types
  has_many :projects, through: :projects_report_types
  has_many :statuses_report_types
  has_many :statuses, through: :statuses_report_types
  has_many :reports
end

app/controllers/report_types_controller.rb
class ReportTypesController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_report_type, only: [:edit]

  # GET /report_types
  # GET /report_types.json
  def index
    @report_types = ReportType.all
  end

  # GET /report_types/new
  def new
    @report_type = ReportType.new
  end

  # GET /report_types/1/edit
  def edit
    set_report_type
  end

  def show
    set_report_type
  end

  # PATCH/PUT /report_types/1
  def update
    set_report_type
    respond_to do |format|
      if @report_type.update_attributes(update_report_type_params)
        format.html do
          redirect_to report_types_path
        end
        format.json { render json: @report_type.to_json}
      else
        format.html { render :edit }
        format.json { render json: @report_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /report_types
  # POST /report_types.json
  def create
    @report_type = ReportType.new(update_report_type_params)
    @report_type.employee_ids.shift
    @report_type.component_ids.shift
    @report_type.project_ids.shift
    @report_type.business_ids.shift
    @report_type.status_ids.shift

    respond_to do |format|
      if @report_type.save!
        # flash[:success] = "Report types has been created successfully"
        # redirect_to report_types_path
        format.html do
          redirect_to report_types_path
        end
        format.json { render json: @report_type.to_json}
      else
        format.html { render :new }
        format.json { render json: @report_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /report_types/1
  # DELETE /report_types/1.json
  def destroy
    @report_type = ReportType.find(params[:id])
    BusinessesReportType.where("report_type_id = ?", @report_type.id).each {|brt| brt.destroy}
    ComponentsReportType.where("report_type_id = ?", @report_type.id).each {|crt| crt.destroy}
    EmployeesReportType.where("report_type_id = ?", @report_type.id).each {|ert| ert.destroy}
    ProjectsReportType.where("report_type_id = ?", @report_type.id).each {|prt| prt.destroy}
    StatusesReportType.where("report_type_id = ?", @report_type.id).each {|srt| srt.destroy}
    @report_type.destroy
    respond_to do |format|
      format.html { redirect_to report_types_url, notice: 'Report type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_report_type
    @report_type = ReportType.find(params[:id])
  end

  def update_report_type_params
    params.require(:report_type).permit(:name, :employee_ids => [], :component_ids => [], :business_ids => [], :project_ids => [], :status_ids => [])
    # params.require(:report_type).permit!
  end

end

app/helpers/report_types_helper.rb
module ReportTypesHelper
end

app/views/report_types/_form.html.erb
<% if @report_type.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@report_type.errors.count, "error") %> prohibited this report type from being saved:</h2>

    <ul>
      <% @report_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field" id="report_name">
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, placeholder: "Report Type's name", :class => "form-control" %>
</div>

<div class="field" id="settings">
  <%= f.label :employee_ids %>
  <ul>
    <%= f.collection_check_boxes :employee_ids, Employee.all, :id, :email, :class => "form-control" %>
  </ul>
  <%= f.label :component_ids %>
  <ul>
    <%= f.collection_check_boxes :component_ids, Component.all, :id, :name, :class => "form-control" %>
  </ul>
  <%= f.label :business_ids %>
  <ul>
    <%= f.collection_check_boxes :business_ids, Business.all, :id, :name, :class => "form-control" %>
  </ul>
  <%= f.label :project_ids %>
  <ul>
    <%= f.collection_check_boxes :project_ids, Project.all, :id, :name, :class => "form-control" %>
  </ul>
  <%= f.label :status_ids %>
  <ul>
    <%= f.collection_check_boxes :status_ids, Status.all, :id, :name, :class => "form-control" %>
  </ul>
</div>

app/views/report_types/edit.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Edit Report Type") %>
  <center><h1>Edit report types</h1></center>
  <%= form_for @report_type do |f| %>
    <%= render 'shared/error_messages' %>
    <%= render 'report_types/form', f: f %>
    <%= f.submit "Save", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

<%= link_to 'Back', report_types_path %>

app/views/report_types/index.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Report types")%>
  <center><h1>Report types</h1></center>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Business</th>
        <th>Project</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @report_types.each do |report_type| %>
        <tr>
          <td><%= report_type.name %>
          <td>
            <% BusinessesReportType.where(report_type_id: report_type.id).each do |b| %>
              <%= Business.find(b.business_id).name %><br>
            <% end %>
          </td>
          <td>
            <% ProjectsReportType.where(report_type_id: report_type.id).each do |p| %>
              <%= Project.find(p.project_id).name %> (<%= Project.find(p.project_id).prefix %>)<br>
            <% end %>
          </td>
          <td>
            <% EmployeesReportType.where(report_type_id: report_type.id).each do |e| %>
              <%= Employee.find(e.employee_id).display_name %><br>
            <% end %>
          </td>
          <td><%= button_to 'Show', report_type_path(report_type), method: :get, class: 'btn btn-info btn-xs' %></td>
          <td><%= button_to 'Edit', edit_report_type_path(report_type), method: :get, class: 'btn btn-info btn-xs' %></td>
          <td><%= link_to 'Destroy', report_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Report Type', new_report_type_path %>

app/views/report_types/new.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "New Report Type") %>
  <center><h1>New report types</h1></center>
  <%= form_for(@report_type, :url => url_for(:controller => 'report_types', :action => 'index')) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= render 'report_types/form', f: f %>
    <%= f.submit "Save", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

<%= link_to 'Back', report_types_path %>

app/views/report_types/show.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Report Type")%>
  <center><h1>Report Type</h1></center>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Employees</th>
        <th>Components</th>
        <th>Business areas</th>
        <th>Projects</th>
        <th>Jira statuses</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @report_type.name %></td>
        <td><% EmployeesReportType.where("report_type_id = #{@report_type.id}").each do |value| %>
          <%= Employee.find(value.employee_id).email %><br>
        <% end %></td>
        <td><% ComponentsReportType.where("report_type_id = #{@report_type.id}").each do |value| %>
          <%= Component.find(value.component_id).name %><br>
        <% end %></td>
        <td><% BusinessesReportType.where("report_type_id = #{@report_type.id}").each do |value| %>
          <%= Business.find(value.business_id).name %><br>
        <% end %></td>
        <td><% ProjectsReportType.where("report_type_id = #{@report_type.id}").each do |value| %>
          <%= Project.find(value.project_id).prefix %><br>
        <% end %></td>
        <td><% StatusesReportType.where("report_type_id = #{@report_type.id}").each do |value| %>
          <%= Status.find(value.status_id).name %><br>
        <% end %></td>
        <td><%= button_to 'Edit', edit_report_type_path(@report_type), method: :get, class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', @report_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </tbody>
  </table>
</div>
<%= link_to 'Back', report_types_path %>