config/routes.rb
Rails.application.routes.draw do

  resources :show_results
  resources :overtimes, :except => [:index, :edit, :show, :new]
  resources :vacations, :except => [:index, :edit, :show, :new]
  resources :report_results, :except => [:edit, :show, :destroy]
  resources :global_settings do
    collection do
      get :get, to: "global_settings#get"
    end
  end
  resources :issues
  resources :issue_histories
  resources :businesses, :except => [:show, :destroy, :create, :new]

  resources :report_types
  resources :components, :except => [:edit, :show, :update, :destroy, :new] 
  resources :projects, :except => [:show]

  resources :statuses, :except => [:show] do
    collection do
      get :refresh, to: "statuses#refresh"
    end
  end
  
  resources :reports do 
    get :get_report, to: "reports#get_report"
    get :get_results, to: "reports#get_results"
  end
  get 'reports/index'

  resources :employees, :except => [:destroy, :create, :new] do
    get :hide_and_show
    collection do
      get :refresh, to: "employees#refresh"
    end
  end

  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations",
    :unlocks => "users/unlocks",
    :omniauth => "users/omniauth"
  } 

  devise_scope :user do
    # get 'signup', to: "users/registrations#new"
    # get 'signin', to: "users/sessions#new"
    get 'users/sign_out', to: "users/sessions#destroy"
  end

  resources :users
    
  root 'reports#index'
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :report_type

  has_many :vacations_reports
  has_many :vacations, through: :vacations_reports
  has_many :overtimes_reports
  has_many :overtimes, through: :overtimes_reports
end

app/models/report_type.rb
class ReportType < ApplicationRecord
  has_many :employees_report_types
  has_many :employees, through: :employees_report_types
  has_many :components_report_types
  has_many :components, through: :components_report_types
  has_many :businesses_report_types
  has_many :businesses, through: :businesses_report_types
  has_many :projects_report_types
  has_many :projects, through: :projects_report_types
  has_many :statuses_report_types
  has_many :statuses, through: :statuses_report_types
  has_many :reports
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_report, only: [:edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])
  end

  # GET /reports/new
  def new
    @report = Report.new
    @vacation = Vacation.new
    @overtime = Overtime.new
  end

  def get_report
    # ReportResult.create(params)
    # redirect_to new_report_result_path(params[:report_id])
    report = Report.find(params[:report_id])

    EmployeesReportType.where(report_type_id: report.report_type_id).each do |employee|
      rrs = ReportResultsService.new(report.from_date, report.to_date, employee.employee_id, report.id)
      rrs.set_spent_times
    end

    EmployeesReportType.where(report_type_id: report.report_type_id).each do |employee|
      rrs = ReportResultsService.new(report.from_date, report.to_date, employee.employee_id, report.id)
      rrs.set_calculated_work_hours
    end

    redirect_to report_results_path
  end

  def get_results
    @report = Report.find(params[:report_id])
    # @results = FullReportResultsView.where(report_id: @report.id)
    # @businesses = FullReportResultsView.select([:business]).where(report_id: @report.id).group(:business).order(:business)
    # @projects = FullReportResultsView.select([:project]).where(report_id: @report.id).group(:project).order(:project)
    @templates = ShowResult.all
    respond_to do |format|
        format.html
        format.pdf do
            render pdf: "report_#{Time.now.to_i}",
                template: "reports_controller/get_results.html.erb",
                layout: 'pdf.html'
        end
    end
  end

  # GET /reports/1/edit
  def edit
    @vacation = Vacation.new
    @overtime = Overtime.new
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        update_vacation_report_id
        update_overtime_report_id
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    ReportResult.where(report_id: @report.id).each { |rr| rr.destroy}
    Vacation.where(report_id: @report.id).each { |v| v.destroy }
    Overtime.where(report_id: @report.id).each { |o| o.destroy }
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :from_date, :to_date, :report_type_id)
      # params.require(:report).permit!
    end

    def update_overtime_report_id
      Overtime.where(report_id: nil).each do |o|
        o.report_id = @report.id
        o.save!
      end
    end

    def update_vacation_report_id
      Vacation.where(report_id: nil).each do |v|
        v.report_id = @report.id
        v.save!
      end
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<% if @report.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

    <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field" id="report_name">
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, placeholder: "Report's name", :class => "form-control" %>
</div>

<div class="field" id="from_date">
  <%= f.label :from_date %>
  <%= f.date_field :from_date, autocomplete: "off", placeholder: "YYYY-MM-DD", :class => "form-control" %>
</div>

<div class="field" id="to_date">
  <%= f.label :to_date %>
  <%= f.date_field :to_date, autocomplete: "off", placeholder: "YYYY-MM-DD", :class => "form-control" %>
</div>

<div class="field" id="report_type">
  <%= f.label :report_type_id %>
  <%= f.collection_select :report_type_id, ReportType.all, :id, :name, :class=> "form-control" %>
</div>

app/views/reports/_form_for_overtimes.html.erb
<div class="field" id="overtime">
  <%= f.label :overtimes %>
  <div class="input_group" %>
    <%= f.collection_select :employee_id, Employee.all, :id, :display_name, class: 'form-control' %>
    <%= f.label :start_date %>
    <%= f.date_field :start_date, autocomplete: "off", placeholder: "YYYY-MM-DD", class: 'form-control' %>
    <%= f.label :end_date %>
    <%= f.date_field :end_date, autocomplete: "off", placeholder: "YYYY-MM-DD", class: 'form-control' %>
    <%= f.label :overtime_sum_hours %>
    <%= f.number_field :hours, class: 'form-control' %>
    <%= f.hidden_field :report_id, value: @report.id %>
    <%= button_to 'Add', overtimes_path, method: :post, class: 'btn btn-info btn-xs' %>
  </div>
</div>

app/views/reports/_form_for_vacations.html.erb
<div class="field" id="vacation">
  <%= f.label :vacations %>
  <div class="input_group" %>
    <%= f.collection_select :employee_id, Employee.all, :id, :display_name, placeholder: "", class: 'form-control' %>
    <%= f.label :start_date %>
    <%= f.date_field :start_date, autocomplete: "off", placeholder: "YYYY-MM-DD", class: 'form-control' %>
    <%= f.label :end_date %>
    <%= f.date_field :end_date, autocomplete: "off", placeholder: "YYYY-MM-DD", class: 'form-control' %>
    <%= f.hidden_field :report_id, value: @report.id %>
    <%= button_to 'Add', vacations_path, method: :post, class: 'btn btn-info btn-xs' %>
  </div>
</div>

app/views/reports/edit.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Reports") %>
  <center><h1>Edit reports</h1></center>

  <div class="grid">
    <div class="row">
      <%= form_for(@report) do |f| %>
        <%= render 'shared/error_messages' %>
        <div class="col-md-12">
          <%= render 'form', f: f %>
        </div>

        <div class="action" id="update">
          <%= f.submit "Update", class: "btn btn-large btn-primary" %>
        </div>
        <div id="cancel">
          <%= link_to 'Cancel', reports_path, class: "btn btn-large" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="raw">
    <div class="col-md-7 col-md-offset-3 main">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#vacation" data-toggle="tab">Vacations</a></li>
        <li><a href="#overtime" data-toggle="tab">Overtimes</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="vacation">
          <% if Vacation.where(report_id: @report.id).count > 0 %>
            <table>
              <thead>
                <tr>
                  <th>Employee</th>
                  <th>From date</th>
                  <th>To date</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% Vacation.where(report_id: @report.id).each do |v| %>
                  <tr>
                    <td><%= Employee.find(v.employee_id).display_name %></td>
                    <td><%= v.start_date %></td>
                    <td><%= v.end_date %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
          <br>
          <%= form_for(@vacation) do |f| %>
            <%= render 'shared/error_messages' %>
            <%= render 'reports/form_for_vacations', f: f %>
            <%= f.submit "Save", class: "btn btn-large btn-primary" %>
          <% end %>
        </div>

        <div class="tab-pane" id="overtime">
          <% if Overtime.where(report_id: @report.id).count > 0 %>
            <table>
              <thead>
                <tr>
                  <th>Employee</th>
                  <th>From date</th>
                  <th>To date</th>
                  <th>Hours</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% Overtime.where(report_id: @report.id).each do |o| %>
                  <tr>
                    <td><%= Employee.find(o.employee_id).display_name %></td>
                    <td><%= o.start_date %></td>
                    <td><%= o.end_date %></td>
                    <td><%= o.hours %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
          <br>
          <%= form_for(@overtime) do |f| %>
            <%= render 'shared/error_messages' %>
            <%= render 'reports/form_for_overtimes', f: f %>
            <%= f.submit "Save", class: "btn btn-large btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/get_results.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Results for #{@report.id} Report")%>
  <center><h1>Result of <%= @report.name %></h1></center>

  <ul class="nav nav-tabs">
    <% @templates.each do |temp| %>
      <li><a href="#<%= temp.id %>" data-toggle="tab"><%= temp.name %></a></li>
    <% end %>
  </ul>

  <div class="tab-content">
    <% @templates.each do |temp| %>
      <% t = temp.template.gsub! '@report.id', "#{@report.id}" %>
      <% erb = ERB.new(temp.template) %>
      <div class="tab-pane" id="<%= temp.id %>"><%= render :inline => erb.result %></div>
    <% end %>
  </div>
</div>
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Reports")%>
  <center><h1>Reports</h1></center>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>From</th>
        <th>To</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% if current_user != nil %>
        <% @reports.each do |report| %>
          <tr>
            <td><%= report.name %></td>
            <td><%= report.from_date %></td>
            <td><%= report.to_date %></td>
            <td><%= ReportType.find(report.report_type_id).name %></td>
            <td><%= button_to 'Show', report, method: :get, class: 'btn btn-info btn-xs' %></td>
            <td><%= button_to 'Edit', edit_report_path(report), method: :get, class: 'btn btn-info btn-xs' %></td>
            <td><% if !ReportResult.find_by_report_id(report.id).nil? %>
              <%= button_to 'Resuls', report_get_results_path(report), method: :get, class: 'btn btn-info btn-xs' %>
            <% end %></td>
            <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<div class="grid">
  <div class="row">
    <div class="col-md-6 col-md-push-3">
      <%= provide(:title, "Create new report") %>
      <center><h1 >Create new report</h1></center>
      <%= form_for(@report) do |f| %>
        <div class="col-md-12">
          <%= render 'shared/error_messages' %>
        <div class="col-md-12">
          <%= render 'form', f: f %>
        </div>
        <div class="actions shared_links" id="submit">
            <%= f.submit "Create", class: "btn btn-large btn-primary" %>
          </div>
          <div id="cancel">
            <%= link_to 'Cancel', reports_path, class: "btn btn-large" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="raw">
    <div class="col-md-6 col-md-push-3">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#vacations" data-toggle="tab">Vacations</a></li>
        <li><a href="#overtimes" data-toggle="tab">Overtimes</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="vacations">
          <% if (Vacation.count > 0) && (Vacation.where(report_id: nil).count > 0) %>
            <table>
              <thead>
                <tr>
                  <th>Employee</th>
                  <th>From date</th>
                  <th>To date</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% Vacation.where(report_id: @report.id).each do |v| %>
                  <tr>
                    <td><%= Employee.find(v.employee_id).display_name %></td>
                    <td><%= v.start_date %></td>
                    <td><%= v.end_date %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
          <br>
          <%= form_for(@vacation) do |f| %>
            <%= render 'shared/error_messages' %>
            <%= render 'reports/form_for_vacations', f: f %>
            <%= f.submit "Save", class: "btn btn-large btn-primary" %>
          <% end %>
        </div>

        <div class="tab-pane" id="overtimes">
          <% if (Overtime.count > 0) && (Overtime.where(report_id: nil).count > 0) %>
            <table>
              <thead>
                <tr>
                  <th>Employee</th>
                  <th>From date</th>
                  <th>To date</th>
                  <th>Hours</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% Overtime.where(report_id: @report.id).each do |o| %>
                  <tr>
                    <td><%= Employee.find(o.employee_id).display_name %></td>
                    <td><%= o.start_date %></td>
                    <td><%= o.end_date %></td>
                    <td><%= o.hours %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
          <br>
          <%= form_for(@overtime) do |f| %>
            <%= render 'shared/error_messages' %>
            <%= render 'reports/form_for_overtimes', f: f %>
            <%= f.submit "Save", class: "btn btn-large btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/show.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Report")%>
  <center><h1>Report</h1></center>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>From</th>
        <th>To</th>
        <th>Vacations</th>
        <th>Overtimes</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @report.name %></td>
        <td><%= @report.from_date %></td>
        <td><%= @report.to_date %></td>
        <td>
          <% Vacation.where(report_id: @report.id).each do |v| %>
            <%= Employee.find(v.employee_id).display_name %><br>
          <% end %>
        </td>
        <td>
          <% Overtime.where(report_id: @report.id).each do |o| %>
            <%= Employee.find(o.employee_id).display_name %><br>
          <% end %>
        </td>
        <td><%= button_to 'Get', report_get_report_path(@report), method: :get, class: 'btn btn-info btn-xs' %></td>
        <td><%= button_to 'Edit', edit_report_path(@report), method: :get, class: 'btn btn-info btn-xs' %></td>
          <td><% if !ReportResult.find_by_report_id(@report.id).nil? %>
            <%= button_to 'Resuls', report_get_results_path(@report), method: :get, class: 'btn btn-info btn-xs' %>
          <% end %></td>
        <td><%= link_to 'Destroy', @report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </tbody>
  </table>
</div>
<%= link_to 'Back', reports_path %>