config/routes.rb
Rails.application.routes.draw do

  resources :show_results
  resources :overtimes, :except => [:index, :edit, :show, :new]
  resources :vacations, :except => [:index, :edit, :show, :new]
  resources :report_results, :except => [:edit, :show, :destroy]
  resources :global_settings do
    collection do
      get :get, to: "global_settings#get"
    end
  end
  resources :issues
  resources :issue_histories
  resources :businesses, :except => [:show, :destroy, :create, :new]

  resources :report_types
  resources :components, :except => [:edit, :show, :update, :destroy, :new] 
  resources :projects, :except => [:show]

  resources :statuses, :except => [:show] do
    collection do
      get :refresh, to: "statuses#refresh"
    end
  end
  
  resources :reports do 
    get :get_report, to: "reports#get_report"
    get :get_results, to: "reports#get_results"
  end
  get 'reports/index'

  resources :employees, :except => [:destroy, :create, :new] do
    get :hide_and_show
    collection do
      get :refresh, to: "employees#refresh"
    end
  end

  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations",
    :unlocks => "users/unlocks",
    :omniauth => "users/omniauth"
  } 

  devise_scope :user do
    # get 'signup', to: "users/registrations#new"
    # get 'signin', to: "users/sessions#new"
    get 'users/sign_out', to: "users/sessions#destroy"
  end

  resources :users
    
  root 'reports#index'
end

app/models/business.rb
class Business < ApplicationRecord
  has_many :businesses_issues
  has_many :issues, through: :businesses_issues
  has_many :businesses_report_types
  has_many :report_types, through: :businesses_report_types
  validates_uniqueness_of :name
  validates_uniqueness_of :jira_name
end

app/models/component.rb
class Component < ApplicationRecord
  has_many :components_issues
  has_many :issues, through: :components_issues
  has_many :components_report_types
  has_many :report_types, through: :components_report_types
  validates_uniqueness_of :name
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :issue_histories

  has_many :employees_report_types
  has_many :report_types, through: :employees_report_types

end

app/models/global_setting.rb
class GlobalSetting < ApplicationRecord
  before_save :only_one_active
  validates :region, :presence => true

  private

  def only_one_active
    if self.active && !GlobalSetting.find_by(active: true).nil?
      old_active = GlobalSetting.find_by(active: true)
      old_active.active = false
      old_active.save
    end
  end

end

app/models/issue.rb
class Issue < ApplicationRecord
  has_many :issue_histories
  has_many :components_issues
  has_many :components, through: :components_issues
  has_many :businesses_issues
  has_many :businesses, through: :businesses_issues
  has_many :projects

  validates_uniqueness_of :issue_key
  validates_uniqueness_of :jira_id_tag

  paginates_per = 50

  def self.search(term, page)
    if term
      where('issue_key LIKE ?', :term).order('issue_key ASC').page(current_page)
    else
      # note: default is all, just sorted
      order('issue_key ASC').page(current_page) 
    end
  end
end

app/models/issue_history.rb
class IssueHistory < ApplicationRecord
  
  belongs_to :issue
  belongs_to :status
  
  validates_uniqueness_of :changelog_id_tag, scope: :issue_id
  
  def get_days
    days = self.duration / 3600 / 24
    return days.to_i
  end

  def get_hours
    hours = (self.duration / 3600) % 24
    return hours.to_i
  end

  def get_minutes
    minutes = 0.0
    # Avoid devision by 0 (the if tag) 
    # Duration is in seconds
    minutes = ( (self.duration / 3600) % (self.duration / 3600).to_i) * 60 if self.duration > 3600
    return minutes.round
  end

end

app/models/overtime.rb
class Overtime < ApplicationRecord
  belongs_to :employee

  has_many :overtimes_reports
  has_many :reports, through: :overtimes_reports

  validates_uniqueness_of :employee_id, scope: :report_id
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :issues
  has_many :projects_report_types
  has_many :report_types, through: :projects_report_types
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :report_type

  has_many :vacations_reports
  has_many :vacations, through: :vacations_reports
  has_many :overtimes_reports
  has_many :overtimes, through: :overtimes_reports
end

app/models/report_result.rb
class ReportResult < ApplicationRecord
  has_many :employees
  has_many :issues
  has_many :reports
end

app/models/report_type.rb
class ReportType < ApplicationRecord
  has_many :employees_report_types
  has_many :employees, through: :employees_report_types
  has_many :components_report_types
  has_many :components, through: :components_report_types
  has_many :businesses_report_types
  has_many :businesses, through: :businesses_report_types
  has_many :projects_report_types
  has_many :projects, through: :projects_report_types
  has_many :statuses_report_types
  has_many :statuses, through: :statuses_report_types
  has_many :reports
end

app/models/show_result.rb
class ShowResult < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :issue_histories
  has_many :statuses_report_types
  has_many :report_types, through: :statuses_report_types
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX}
  
end

app/models/vacation.rb
class Vacation < ApplicationRecord
  belongs_to :employee

  has_many :vacations_reports
  has_many :reports, through: :vacations_reports

  # validates_uniqueness_of :employee_id, :start_date, scope: :report_id
end

app/controllers/show_results_controller.rb
class ShowResultsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_show_result, only: [:show, :edit, :update, :destroy]

  # GET /show_results
  def index
    @show_results = ShowResult.all
  end

  # GET /show_results/1
  def show
  end

  # GET /show_results/new
  def new
    @show_result = ShowResult.new
  end

  # GET /show_results/1/edit
  def edit
  end

  # POST /show_results
  def create
    @show_result = ShowResult.new(show_result_params)

    if @show_result.save
      redirect_to @show_result, notice: 'Result view was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /show_results/1
  def update
    if @show_result.update(show_result_params)
      redirect_to @show_result, notice: 'Result view was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /show_results/1
  def destroy
    @show_result.destroy
    redirect_to show_results_url, notice: 'Result view was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_show_result
    @show_result = ShowResult.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def show_result_params
    params.require(:show_result).permit(:name, :template)
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def signed_in?
    !current_user.nil?
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/show_results_helper.rb
module ShowResultsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/show_results/_form.html.erb
<% if @show_result.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@show_result.errors.count, "error") %> prohibited this show result from being saved:</h2>

    <ul>
      <% @show_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field" id="template_name">
  <%= f.label :show_result_template %>
  <%= f.text_field :name, autofocus: true, placeholder: "View template's name", :class => "form-control" %>
</div>

<div class="field" id="template">
  <%= f.label :template %>
  <%= f.text_area :template, cols: "75", rows: "10" %>
</div>

app/views/show_results/edit.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Edit Template") %>
  <center><h1>Edit views template</h1></center>
  <%= form_for @show_result do |f| %>
    <%= render 'shared/error_messages' %>
    <%= render 'form', f: f %>
    <%= f.submit "Save", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

<%= link_to 'Back', show_results_path %>

app/views/show_results/index.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Different views for report results")%>
  <center><h1>View templates</h1></center>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @show_results.each do |show_result| %>
        <tr>
          <td><%= show_result.name %>
          <td><%= button_to 'Show', show_result_path(show_result), method: :get, class: 'btn btn-info btn-xs' %></td>
          <td><%= button_to 'Edit', edit_show_result_path(show_result), method: :get, class: 'btn btn-info btn-xs' %></td>
          <td><%= link_to 'Destroy', show_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New View Template', new_show_result_path %>

app/views/show_results/new.html.erb
<div class="col-md-6 col-md-push-3">
  <%= provide(:title, "New view template") %>
  <center><h1 >Create new template</h1></center>
  <%= form_for(@show_result) do |f| %>
    <div class="col-md-12">
      <%= render 'shared/error_messages' %>
    <div class="col-md-12">
      <%= render 'form', f: f %>
    </div>
      <div class="actions shared_links" id="submit">
        <%= f.submit "Create", class: "btn btn-large btn-primary" %>
      </div>
      <div id="cancel">
        <%= link_to 'Cancel', show_results_path, class: "btn btn-large" %>
      </div>
    </div>
  <% end %>  
</div>

app/views/show_results/show.html.erb
<div class="col-md-7 col-md-offset-3 main">
  <% provide(:title, "Result view template")%>
  <center><h1><%= @show_result.name %></h1></center>
  <table>
    <tbody>
      <tr>
        <td><%= @show_result.template %></td>
      </tr>
      <tr>
        <td><%= button_to 'Edit', edit_show_result_path(@show_result), method: :get, class: 'btn btn-info btn-xs' %>
        <%= link_to 'Destroy', @show_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </tbody>
  </table>
</div>
<%= link_to 'Back', show_result_path %>